### ISSUE TITLE
family argument in fit_hal is funky

### ISSUE THREAD

**Issue by jlstiles** [jeremyrcoyle/hal9001#10]
I am getting weird answers when inputting the family argument

```
devtools::install_github("jlstiles/Simulations")
library(hal9001)
library(Simulations)

n=200
data =gendata(n, g0=g0_linear,Q0=Q0_trig1)
X=data
X$Y=NULL
Y=data$Y
X0=X1=X
X0$A=0
X1$A=1
newdata = rbind(X,X1,X0)

time = proc.time()
halres9001 <- fit_hal(Y = Y, X = X, family = "binomial")
timehal9001 = proc.time() - time

Qk = predict(halres9001, new_data = newdata)[1:n]
Q1k = predict(halres9001, new_data = newdata)[n+1:n]
Q0k = predict(halres9001, new_data = newdata)[2*n+1:n]
esthal9001 = var(Q1k-Q0k)
esthal9001ATE = mean(Q1k-Q0k)

esthalATE
esthal9001ATE
```

**Comment by nhejazi** [comment]
`family` is passed directly from `fit_hal` to `cv.glmnet`. Could you clarify what `g0_linear` and `Q0_trig1` are in your example above? (I can't reproduce the reported error without them.)

**Comment by jeremyrcoyle** [comment]
The issue is that predict is currently hard coded to x*coef, so predictions when family="binomial" are on the logit scale. Side note: halclassic ignores its family argument https://github.com/benkeser/halplus/blob/master/R/hal.R#L190 so comparisons should be made for gaussian only

**Comment by nhejazi** [comment]
Also, including an argument `family` may be inappropriate for theoretical reasons. See the comments in [this issue](https://github.com/benkeser/halplus/issues/3) (in the `halplus` repo) for details.

**Comment by jeremyrcoyle** [comment]
Good to know. So what should we do going forward? Disable support for passing `family` to `cv.glmnet` in `hal9001` (and maybe implement bounding instead), or support it correctly?

**Comment by jeremyrcoyle** [comment]
Also, @jlstiles to @nhejazi's point earlier, it would be helpful if you could try to make your examples minimum and reproducible. Here's a discussion on the topic: https://stackoverflow.com/a/5963610/3243525

**Comment by benkeser** [comment]
I think we're good to keep the family argument in. I was too lazy to think it through previously, but I think Jonathan has convinced me that it's kosher.

**Comment by nhejazi** [comment]
Resolved as part of https://github.com/jeremyrcoyle/hal9001/pull/24
