### ISSUE TITLE
logit link for binomial outcomes

### ISSUE THREAD

**Issue by nhejazi** [jeremyrcoyle/hal9001#13]
The current custom implementation of the Lasso only supports continuous outcomes (that is, the case of the Gaussian error family). Some degree of revision will be necessary to support other types of outcomes, the most common case being that of binary outcomes.

For the time being, those interested in using Lasso with the binary outcomes can simply use `cv.glmnet` and pass it the option `family = "binomial"`.

**Comment by nhejazi** [comment]
Currently, even passing `family = "binomial"` does not work correctly, as the method `predict.hal9001` does not respect the specification of this argument, even when though it is pased to `cv.glmnet`.

Further, an error/warning should be added to `cv_lasso` to warn the user or stop the current estimation procedure when `fit_type = "origami"` and the extra argument `family = "binomial"` is passed in.

**Comment by wilsoncai1992** [comment]
I have been using `family=binomial` lately. Would greatly appreciate if I can get updated on this issue.

**Comment by nhejazi** [comment]
The setting `family = "binomial"` is now correctly supported when using `fit_type = "origami"` in `fit_hal`

**Comment by nhejazi** [comment]
Resolved as part of https://github.com/jeremyrcoyle/hal9001/pull/24. A custom implementation of IRLS to support `family = "binomial"` for `fit_type = "origami"` has been moved to #25
