### ISSUE TITLE
supporting active-set convergence

### ISSUE THREAD

**Issue by nhejazi** [jeremyrcoyle/hal9001#14]
In their Lasso implementation in the `glmnet` package, Hastie et al. note that
```
Considerable speedup is obtained by organizing the iterations around the
active set of features—those with nonzero coefficients. After a complete cycle
through all the variables, we iterate on only the active set till convergence. If
another complete cycle does not change the active set, we are done, otherwise
the process is repeated. Active-set convergence is also mentioned in Meier
et al. [2008] and Krishnapuram and Hartemink [2005].
```
We could very likely speed up our implementation by incorporating this procedure.

**Comment by nhejazi** [comment]
@jeremyrcoyle -- This is already incorporated in an un-pushed commit, yes?

**Comment by jeremyrcoyle** [comment]
Yes, but a kludgey version, definitely be more work to be done on this one

**Comment by jeremyrcoyle** [comment]
Fixed in https://github.com/jeremyrcoyle/hal9001/pull/23
