### ISSUE TITLE
Use hal9001 in superlearner() in R

### ISSUE THREAD

**Issue by TerrySun920302** [jeremyrcoyle/hal9001#30]
Hi, 

I am tryiny to add the "SL.hal9001" function to SuperLearner() function, and there is no problem to fit such model. But when I try to do prediction with new data set, by using predict(mod, newdataset, onlyST = T), it returns me "Error in predict.hal9001(object$object, new_data = newX) : argument "newX" is missing, with no default" if the weight for hal9001 is not 0. I ma wondering how to deal with this case?

Best,

Hao

**Comment by nhejazi** [comment]
Thanks for your note. Would you mind posting a _minimally reproducible example_ (MRE) of a case where this error arises? The process of tracking down a possible bug and helping you resolve this error will be made significantly easier by having example code (that leads to this error) to run.

**Comment by TerrySun920302** [comment]
Thanks for you reply. Please find a the attached short code.

Best,

Hao

#################### training data ###############################################################
x1 <- rnorm(500)
x2 <- rnorm(500)
y <- x1^2 + abs(x2) + rnorm(500)
x <- data.frame(x1, x2)


#################### test data ###################################################################
x1new <- rnorm(500)
x2new <- rnorm(500)
xnew <- data.frame(x1 = x1new, x2 = x2new)


############# when hal9001 is added to the library ############################################### 
sl.lib=c("SL.earth","SL.gam","SL.glm","SL.glm.interaction","SL.mean","SL.ranger","SL.hal9001")
SL <- SuperLearner(Y=y, X=x, SL.library=sl.lib)
pre <- predict(SL, xnew) #### error in this step

############# when hal9001 is not added to the library ############################################### 
sl.lib=c("SL.earth","SL.gam","SL.glm","SL.glm.interaction","SL.mean","SL.ranger")
SL <- SuperLearner(Y=y, X=x, SL.library=sl.lib)
pre <- predict(SL, xnew)

**Comment by nhejazi** [comment]
Thank you again for pointing out this bug. The PR #31 resolves the error that you report here. This may be easily confirmed by running the following example (adapted from your MRE above):

```r
devtools::install_github("jeremyrcoyle/hal9001@sl-wrapper-bug")
library(SuperLearner)

# training data ###############################################################
x1 <- rnorm(500)
x2 <- rnorm(500)
y <- x1^2 + abs(x2) + rnorm(500)
x <- data.frame(x1, x2)

#################### test data ###############################################
x1new <- rnorm(500)
x2new <- rnorm(500)
xnew <- data.frame(x1 = x1new, x2 = x2new)

############# when hal9001 is not added to the library #######################
sl.lib=c("SL.mean", "SL.hal9001")
SL <- SuperLearner(Y = y, X = x, newX = xnew, SL.library = sl.lib)
pre <- predict(SL, newdata = xnew)
```

Please note that, for the time being, this package, `hal9001`, must be installed on the branch `sl-wrapper-bug` (until this is merged into `master` soon), as is done in the first line of the script above. If there are any further issues, please feel free to let us know.
